// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  cruxCore: [
    { type: 'doc', id: 'crux-core/intro' },
    {
      type: 'category',
      label: '⚙️ Core Systems',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'crux-core/basic' },
      ],
    },
  ],
  cruxEnchantsOverhaul: [
    { type: 'doc', id: 'crux-enchants-overhaul/intro' },
    {
      type: 'category',
      label: '⚙️ Core Systems',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'crux-enchants-overhaul/basic' },
      ],
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
